---
- hosts: wordpress
  vars_files:
    - vars/default.yml

  tasks:

  - name: Set Wordpress debugging
    lineinfile: >
      dest={{root_directory}}/wp-config.php line="define('WP_DEBUG', true); define('WP_DEBUG_LOG', true);"
      insertafter="^define\('FS_METHOD'"
      state=present
    when: "{{ debug }}"

  - name: Install WP-CLI
    shell: >
      curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      && mv wp-cli.phar /usr/local/bin/wp
      creates=/usr/local/bin/wp

  - name: Ensure WP-CLI permissions
    file: path=/usr/local/bin/wp state=file mode=755

  - name: Ensure wp-content is world writeable
    file: path={{root_directory}}/wp-content state=directory mode=777 recurse=yes

  - name: Install Wordpress
    command: >
      wp core install --url={{ remote_host_ip }}:{{ host_port }} --allow-root --title="{{title}}" --admin_user={{admin_user}} --admin_password={{admin_pwd}}
      --admin_email={{admin_email}} chdir={{root_directory}}

  - name: Install theme (1/2)
    shell: "mkdir {{root_directory}}/wp-content/themes/{{theme_name}}"

  - name: Install theme (2/2)
    unarchive:
      src: https://drive.google.com/u/0/uc?id=11jf9OOayn1Bxnko7KqC6U854qjEwrFe2&export=download
      dest: "{{root_directory}}/wp-content/themes/{{theme_name}}"
      remote_src: yes

  - name: Activate theme
    command: wp theme activate {{theme_name}} chdir={{root_directory}} --allow-root