---
- hosts: wordpress
  vars_files:
    - vars/default.yml

  tasks:  

  - name: Set Wordpress debugging
    lineinfile: >
      dest={{root_directory}}/wp-config.php line="define('WP_DEBUG', true); define('WP_DEBUG_LOG', true);"
      insertafter="^define\('FS_METHOD'"
      state=present
    when: "{{ debug }}"

  - name: Install Composer
    sudo: true
    shell: >
      curl -sS https://getcomposer.org/installer | php
      && mv composer.phar /usr/local/bin/composer
      creates=/usr/local/bin/composer

  - name: Install WP-CLI
    sudo: true
    shell: >
      curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      && mv wp-cli.phar /usr/local/bin/wp
      creates=/usr/local/bin/wp

  - name: Ensure WP-CLI permissions
    sudo: true
    file: path=/usr/local/bin/wp state=file mode=755

  - name: Ensure wp-content is world writeable
    sudo: true
    file: path={{root_directory}}/wp-content state=directory mode=777 recurse=yes

  - name: Install Wordpress
    command: >
      wp core install --url={{url}} --title="{{title}}" --admin_user={{admin_user}} --admin_password={{admin_pwd}}
      --admin_email={{admin_email}} chdir={{root_directory}}

  - name: Install theme
    git: 
      repo: "{{ theme_repo }}"
      dest: "{{root_directory}}/wp-content/themes/{{theme_name}}"

   - name: Activate theme
     command: wp theme activate {{theme_name}} chdir={{root_directory}}