---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip', 'libapache2-mod-php7.0' ]

#MySQL Settings
db_address: "10.0.1.94"
mysql_root_password: "rootpass"
mysql_db: "wordpress"
mysql_user: "wpuser"
mysql_password: "pass"

#Web Settings
remote_host_ip: ""

#HTTP Settings
http_host: "centel"
http_conf: "centel.conf"
http_port: "80"

#wp-cli
root_directory: /var/www/centel/wordpress
theme_name: centel
theme_repo: https://github.com/aweiiy/Centel/tree/main/theme
locale: en_EN
title: centel
admin_user: admin
admin_pwd: admin
admin_email: admin@centel.com
debug: true