---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip', 'libapache2-mod-php7.0' ]

#MySQL Settings
mysql_root_password: "root"
mysql_db: "wordpress"
mysql_user: "wordpressUser"
mysql_password: "pass"

#HTTP Settings
http_host: "centel"
http_conf: "centel.conf"
http_port: "80"
